# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0b76cc2b58e9d3509879e00b25515219c1dbddc5a33fbaaa8c361faed6ad8ef26aecf119c586122814407157780c58b8eb203313a750182864ca78d2e031522

test:
  secret_key_base: d96c504f576b1bc87158e8298b93e820b16c07e710e8affe7d73c3b8c7299f3f14e9d4598b265bcce66fcbb914f3539fe3483e465822b8937eafc3f476914c17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
